# Generated by Django 3.2.7 on 2022-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220810_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catagoty',
            field=models.ManyToManyField(to='blog.Catagory', verbose_name='دسته بندی'),
        ),
    ]
