# Generated by Django 3.2.7 on 2022-08-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_catagoty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='catagoty',
            new_name='catagory',
        ),
    ]
