# Generated by Django 3.2.7 on 2022-08-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220811_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.catagory', verbose_name='زیر دسته'),
        ),
        migrations.AlterField(
            model_name='article',
            name='catagory',
            field=models.ManyToManyField(related_name='articles', to='blog.Catagory', verbose_name='دسته بندی'),
        ),
    ]
