# Generated by Django 3.2.7 on 2022-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220811_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'ordering': ['parent__id', 'position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='iamge',
            field=models.ImageField(default='/static/blog/assets/img/home-bg.jpg', upload_to='images', verbose_name='تصویر تیتر سایت'),
            preserve_default=False,
        ),
    ]
