# Generated by Django 3.2.7 on 2022-08-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20220814_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IPAdrress',
            new_name='IPAddress',
        ),
    ]
