# Generated by Django 3.2.7 on 2022-08-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_ipadrress_ipaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آی پی', 'verbose_name_plural': 'آی پی ها'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
